### ISSUE TITLE
Basic finals : date sorting failed to sort + fix

### ISSUE THREAD

**Issue by tobudim** [vercel/next-learn-starter#10]
**What's the issue ?**

I used the Next.js tutorial as the foundation of my first Next blog. ``/lib/posts.js`` sorts posts in a way they are not always sorted.

**How to reproduce this issue ?**

I had this problem with this kind of dates: September 1st, 2nd and 4th. It displayed as such:

- Post about pets - September 2nd, 2020
- Post about tomatoes - September 1st, 2020
- Post about space - September 4th, 2020

You can reproduce it by playing with my code just before and after [this commit](https://github.com/tobudim/next-blog/commit/2d6ef06aa32ba4b627a46f88c60942536711cf3d).

**Where is the issue ?**

https://github.com/vercel/next-learn-starter/blob/d90855ed3f6b6366d3834536f19b5b9cb8de26f3/basics-final/lib/posts.js#L30-L36

**What is the fix ?**

```js
return allPostsData.sort((a, b) => { 
  return new Date(b.date) - new Date(a.date);
 }) 
```

A PR is on its way. I hope it can help out other beginners like me. By the way, awesome tutorial, so clear and easy to understand!

**Comment by leerob** [comment]
Hey! Thanks for reporting this. Unfortunately, I was not able to reproduce with our code. 

![image](https://user-images.githubusercontent.com/9113740/93271427-d2068400-f778-11ea-966a-11a58a74494e.png)

Maybe try starting from our completed example and work backward to see where your code differs 🙏
