### ISSUE TITLE
create-react-app.dev already using prerendering

### ISSUE THREAD

**Issue by Baterka** [vercel/next-learn-starter#21]
In step 3 of tutorial: https://nextjs.org/learn/basics/data-fetching/pre-rendering
there is example of not pre-rendered website:
`Enable JavaScript in your browser and check out this page. This is a plain React.js app built with Create React App.`,
but this website is already prerendered (same result as for https://next-learn-starter.now.sh/)

**Comment by leerob** [comment]
Hello! I just checked and confirmed that the example linked (https://create-react-app.now-examples.now.sh/) **does not work** without having JavaScript enabled. 

I was also able to confirm https://next-learn-starter.now.sh **does work** without JavaScript enabled.
