### ISSUE TITLE
Typescript module type error (ts(2307)) in typescript-final directory

### ISSUE THREAD

**Issue by derekschinke** [vercel/next-learn-starter#32]
After installing Typescript and converting the .js files to .tsx, a bunch of TypeScript errors appear in in the import statements of modules in VSCode. For example, in `date.tsx`:

> Cannot find module 'date-fns' or its corresponding type declarations. ts(2307)

Error appears in VSCode, on M1 Mac. Using Yarn 3.

**Comment by deyvisonpenha** [comment]
@derekschinke did you try to install the types ? like 
```
yarn add -D @types/date-fns
```
I'm using yarn but you can use npm and add this library in development scope.

**Comment by derekschinke** [comment]
`@type/date-fns` is deprecated: https://www.npmjs.com/package/@types/date-fns

It says that it provides its own type definitions, so you don't need it installed.

**Comment by derekschinke** [comment]
Figured it out: an issue with Yarn PnP and Editor SDKs: https://yarnpkg.com/getting-started/editor-sdks

Solved by running `yarn dlx @yarnpkg/pnpify --sdk`.

Sorry bout that!
