### ISSUE TITLE
Getting these errors using any next-js stater template

### ISSUE THREAD

**Issue by bitsper2nd** [vercel/next-learn-starter#37]
Unhandled Runtime Error

Error: No router instance found.
You should only use "next/router" inside the client side of your app.
![Screenshot 2021-06-03 at 21-48-02 Screenshot](https://user-images.githubusercontent.com/22452474/120729510-b9303100-c4b5-11eb-96c2-a1f2de3bde78.png)

Server Error

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

![Screenshot 2021-06-03 at 21-48-12 Screenshot](https://user-images.githubusercontent.com/22452474/120729555-d7962c80-c4b5-11eb-917b-75c06307c6e5.png)

Honestly I'm so confused and frustrated about not being able to run anything locally. I want to learn to use next.js, but I can't see to start with it.

**Comment by bitsper2nd** [comment]
nvm. solved it myself.

**Comment by merchantweb** [comment]
@bitsper2nd  I am at the same point and trying to get started running a next.js app locally. I am getting the exact same message. What did you do to resolve this issue? I know it is my inexperience... trying to get over the learning curve. Thanks!

**Comment by bitsper2nd** [comment]
In my case I forgot to install nextjs on the directory with npm.

**Comment by ronnyek** [comment]
I ran into this problem becasue my c drive was `C` and not `c`.

I work with react apps created with `create-react-app` all day long and don't run into those problems with it.
