### ISSUE TITLE
.css files are duplicated on https://next-learn-starter.now.sh/

### ISSUE THREAD

**Issue by plug-n-play** [vercel/next-learn-starter#4]
On https://next-learn-starter.now.sh/ following CSS files are duplicated:

https://next-learn-starter.now.sh/_next/static/css/dcff670ee14b1f15bf73.css &
https://next-learn-starter.now.sh/_next/static/css/11680bc78302d5568daa.css

![image](https://user-images.githubusercontent.com/6245927/80873144-1e728b00-8cd4-11ea-92a2-81fb28fa34cc.png)

**Comment by chibicode** [comment]
@plug-n-play Thanks! I think one of them is `rel="preload"` and the other is `rel="stylesheet"`?

**Comment by leerob** [comment]
Closing as inactive 👍
