### ISSUE TITLE
Next learn starter app - TypeError: (0 , react_jsx_dev_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxDEV) is not a function

### ISSUE THREAD

**Issue by NFabrizio** [vercel/next-learn-starter#40]
Sorry if this issue has already been reported and resolved. I did a search and could not find anything that matched this issue.

Steps to reproduce:

1. Create a new directory.
2. cd into the new directory.
3. Run the command npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn-starter/tree/master/learn-starter".
4. cd into nextjs-blog directory.
5. Run the command npm run dev.

Expected:
Dev server starts properly.
Actual:
TypeError: (0 , react_jsx_dev_runtime__WEBPACK_IMPORTED_MODULE_0__.jsxDEV) is not a function
at Home (webpack-internal:///./pages/index.js:19:92) 
is displayed in terminal.

System information:
MacOS Catalina
Node v14.16.0 

I have also tried deleting the node_modules and package-lock.json and running npm install again, but I still get the same error.

**Comment by cr4yfish** [comment]
I'm getting issues as well doing the same.

### First issue:
>Unhandled Runtime Error
Error: No router instance found.
You should only use "next/router" on the client side of your app.

### And the second issue:

> Server Error
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the [...]

Note I followed the exact steps from @NFabrizio and did not touch any code myself.

**Comment by langford-bc** [comment]
Hi there. I'm taking a shot in the dark and going through the basics of creating a NextJS app. I've gotten the same error as NFabrizio. 

TypeError: (0 , _lib_posts__WEBPACK_IMPORTED_MODULE_3__.getSortedPostsData) is not a function.

I replaced my code with the code from the directory for learning the basics of NextJS: "If something is not working, make sure your code looks like this."

This code produced the same error.

Can you provide any clarification on what needs to be looked at to resolve this? Many thanks.

<img width="993" alt="NextJS-Basics-Type-Error" src="https://user-images.githubusercontent.com/61123596/127480978-f5ed7515-40c5-4a50-b30d-985dbe4e0d59.png">

**Comment by Dev-Logan-Bennett** [comment]
Hey guys, I know how frustrating it can be, lol. Try using `"remark": "^13.0.0", "remark-html": "^13.0.1",` instead of the updated remark and remark-html libraries, this worked for me.

**Comment by leerob** [comment]
Sorry, I forgot to update this issue - this has been resolved with the correct versions pinned in the docs!

**Comment by imhilla** [comment]
Experienced this issue today.
