### ISSUE TITLE
next-learn-starter/basics-final/Server Error

### ISSUE THREAD

**Issue by osaroDEV** [vercel/next-learn-starter#42]
Error: Must use import to load ES Module: C:\dev\devProjects\next projects\blog-site\nextjs-blog\node_modules\remark\index.js
require() of ES modules is not supported.

**Comment by wcelery** [comment]
Same here with the same error. Repo: https://github.com/wcelery/nextjs-blog/blob/2d842f76af881a8ac80c530772e9b6ee7d942315/lib/posts.js

**Comment by taylor-smith** [comment]
Remark recently switched to ESM in 14.0.0 ([https://github.com/remarkjs/remark/releases/tag/14.0.0](https://github.com/remarkjs/remark/releases/tag/14.0.0)).  Next.js does not support ESM packages out-of-the-box; if you've got version `14.0.0` for `remark` and `remark-html` in your `package.json`, you'll get this error.

It looks like there are some workarounds to support ESM in Next.js: [https://github.com/vercel/next.js/issues/9607](https://github.com/vercel/next.js/issues/9607).

I got around this issue by dropping my versions of `remark` and `remark-html` to 13.0.0 in `package.json`:

```
{
 ...
"dependencies": {
    ...
    "remark": "13.0.0",
    "remark-html": "13.0.0"
  }
}
```

but you could also try implementing one of the workarounds mentioned in the above issue if you really wanted to use `14.0.0`.

**Comment by realdocweird** [comment]
on this post there is another "solution" https://github.com/vercel/next.js/issues/25454

```
import dynamic from 'next/dynamic';
const remark = dynamic(() => import('remark'), { ssr: false });
const html = dynamic(() => import('remark-html'), { ssr: false });
```
but still learning so idk what it actually means but it works lol

**Comment by faouziMohamed** [comment]
> Remark recently switched to ESM in 14.0.0 (https://github.com/remarkjs/remark/releases/tag/14.0.0). Next.js does not support ESM packages out-of-the-box; if you've got version `14.0.0` for `remark` and `remark-html` in your `package.json`, you'll get this error.
> 
> It looks like there are some workarounds to support ESM in Next.js: [vercel/next.js#9607](https://github.com/vercel/next.js/issues/9607).
> 
> I got around this issue by dropping my versions of `remark` and `remark-html` to 13.0.0 in `package.json`:
> 
> ```
> {
>  ...
> "dependencies": {
>     ...
>     "remark": "13.0.0",
>     "remark-html": "13.0.0"
>   }
> }
> ```
> 
> but you could also try implementing one of the workarounds mentioned in the above issue if you really wanted to use `14.0.0`.

This worked for me!

**Comment by leerob** [comment]
The tutorial has been updated to pin the remark versions, and we're working on native ESM support in Next.js!
