### ISSUE TITLE
I've solved the issue with a workaround, simply use query params without a custom server integration, just like below:

### ISSUE THREAD

**Issue by fastengineer** [vercel/next-learn-starter#6]
I think this need to be documented. It saved my day. Without this really difficult to have virtual links.
----
I've solved the issue with a workaround, simply use query params without a custom server integration, just like below:

## Workaround
```js
Router.replace(`/path-to-route?param=${param}&param2=${param2}`, `/path-to-route/${param}/${param2}`, { shallow: true })
```

And then in the page wrap the component with `withRouter`

```js
import { withRouter } from 'next/router';

class YourAwesomeComponent extends React.Component {
	render () {
		const { query } = this.props.router
		return <h1> {query.param} {query.param2} </h1>
	}
}

export default withRouter(YourAwesomeComponent)
```

## Question
In my case the usage of a custom route on `server.js` was unuseful, but what if I need to do custom stuff in my custom route?

_Originally posted by @Rawnly in https://github.com/zeit/next.js/issues/5922#issuecomment-448958614_

**Comment by leerob** [comment]
Hey @fastengineer – thank you for reporting this. At this time, we're not looking to add this to the `next-learn-starter` repo.
