### ISSUE TITLE
date-fns error

### ISSUE THREAD

**Issue by sarahbenjamin** [vercel/next-learn-starter#7]
At step 8  of this link 
https://nextjs.org/learn/basics/dynamic-routes/polishing-index-page
it asks to add the following line to index.js page

import Date from '../components/date'

but the date file is not provided. I got it from the code here but then I am getting the following error.

Module not found: Can't resolve 'date-fns' in '..\nextjs-blog\components'

What am I missing?

**Comment by sarahbenjamin** [comment]
Ok found it, there is  step to install a dependency. 
npm install date-fns

After this the error went away. 
Maybe I missed seeing these steps in the instructions on the tutorial mentioned above.

**Comment by chibicode** [comment]
@sarahbenjamin glad that you were able to resolve the issue. The instruction was on the previous page:

https://nextjs.org/learn/basics/dynamic-routes/polishing-post-page

<img width="723" alt="Screen Shot 2020-06-24 at 5 52 37 PM" src="https://user-images.githubusercontent.com/992008/85641484-8e9ded00-b643-11ea-8fa4-308f7d1c61d8.png">
