### ISSUE TITLE
Missing step > [Assets, Metadata, and CSS > Download Your Profile Picture]

### ISSUE THREAD

**Issue by jmmarco** [vercel/next-learn-starter#8]
It looks like there's a step missing for the lesson [Assets, Metadata, and CSS > Download Your Profile Picture](https://nextjs.org/learn/basics/assets-metadata-css/polishing-layout). You say:
> Create an `images` directory inside of the `public` directory

But there's no `public` folder yet 🤔 

Perhaps add the step:
- Stop the development server, then run `npm run build` to generate the `public` folder.

The whole thing would look like this:

- Download your profile picture from GitHub, Twitter, LinkedIn or elsewhere (or use this file).
- Stop the development server, then run `npm run build` to generate the `public` folder.
- Create an `images` directory inside of the `public` directory.
- Save the picture as `profile.jpg` in the `public/images directory`.
- The image size can be around 400px by 400px.
- You may remove the unused SVG logo file directly under the `public` directory.

**Comment by dodiameer** [comment]
The public folder seems to already exist when you run ```yarn create next-app <directory name>```, with ```favicon.ico``` and ```vercel.svg```. Perhaps you're using an older version of Next? 

I'll make a PR and add the step, it doesn't hurt to do that.

**Comment by dodiameer** [comment]
Never-mind about the PR, this repo doesn't have the tutorial pages.

**Comment by jmmarco** [comment]
Ok @dodiameer hopefully the extra help would help clarify that for others. Thanks!

**Comment by leerob** [comment]
It's possible they've already created a `/public` directory. I think the current state is clear that you'll need a public folder if you don't already have one. Also, you shouldn't need to stop the development server and run `build`. That would generate a production build. `next dev` should work!

If you strongly disagree, let me know. Closing for now.
